#nacos:
#  config:
#    server-addr: ${deveploy.server-url}
#    bootstrap:
#      log-enable: true
#    data-id: GMS-CORE-PRDT.yaml
#    type: yaml
#spring:
#  application:
#    name: GMS-CORE
#  profiles:
#    active: ${deveploy.plateform}

spring:
  application:
    name: VOTE-SYSTEM
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/vote-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 769339438@qq.com
    password: vnmzhwnmxuvjbdfd
    default-encoding: UTF-8

  redis:
    # Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #password:
    # Redis数据库索引（默认为0）
    database: 1
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000


mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lzh.vote.mapper
server:
  port: 9003



#  CREATE DATABASE `vote-system` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';


